apiVersion: v1
kind: Service
metadata:
  name: {{ include "crontab-ui.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crontab-ui.labels" . | nindent 4 }}
  {{- if .Values.tailscale.enabled }}
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: {{ .Values.tailscale.hostname | quote }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "crontab-ui.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
    name: web
